### ISSUE TITLE
upgrade to Neo4j 1.5.M02

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/neoclipse#1]

**Comment by lordkada** [comment]
+1

**Comment by nrkkalyan** [comment]
I upgraded to 1.6-Snapshot yesterday and sent a pull request on this..

**Comment by peterneubauer** [comment]
Very cool thanks a lot! Could you please send in the CLA, http://docs.neo4j.org/chunked/snapshot/cla.html so we can merge, and possibly make you committer on the repo? Would be great.

**Comment by nrkkalyan** [comment]
Ya sure.
