### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nrkkalyan** [neo4j-contrib/neoclipse#16]
Got the exception when performing Search

Dec 25, 2011 3:38:24 AM org.neo4j.neoclipse.graphdb.GraphDbServiceManager logInfo
INFO: connected to embedded neo4j
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at org.neo4j.neoclipse.search.NeoSearchQuery.run(NeoSearchQuery.java:145)
    at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
    at org.apache.lucene.util.SimpleStringInterner.intern(SimpleStringInterner.java:54)
    at org.apache.lucene.util.StringHelper.intern(StringHelper.java:36)
    at org.apache.lucene.index.Term.<init>(Term.java:38)
    at org.apache.lucene.queryParser.QueryParser.getFieldQuery(QueryParser.java:643)
    at org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1421)
    at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1309)
    at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1237)
    at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1226)
    at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
    at org.neo4j.index.impl.lucene.IndexType.query(IndexType.java:281)
    at org.neo4j.index.impl.lucene.LuceneIndex.query(LuceneIndex.java:207)
    at org.neo4j.index.impl.lucene.LuceneIndex.query(LuceneIndex.java:218)
    at org.neo4j.neoclipse.search.NeoSearchQuery.getMatchingNodesFromIndices(NeoSearchQuery.java:196)
    at org.neo4j.neoclipse.search.NeoSearchQuery.access$0(NeoSearchQuery.java:174)
    at org.neo4j.neoclipse.search.NeoSearchQuery$1.call(NeoSearchQuery.java:133)
    at org.neo4j.neoclipse.search.NeoSearchQuery$1.call(NeoSearchQuery.java:1)
    at org.neo4j.neoclipse.graphdb.GraphDbServiceManager$TaskWrapper.call(GraphDbServiceManager.java:242)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
!SESSION 2011-12-25 03:34:34.650 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_01
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.neo4j.neoclipse.neoclipseProduct
Command-line arguments:  -product org.neo4j.neoclipse.neoclipseProduct -data C:\Kalyan\github\nrkkalyan\neoclipse\org.neo4j.neoclipse -dev file:C:/Kalyan/github/nrkkalyan/workspace/.metadata/.plugins/org.eclipse.pde.core/neoclipse.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault

!ENTRY org.eclipse.core.jobs 4 2 2011-12-25 03:38:43.892
!MESSAGE An internal error occurred during: "Neo4j Search".
!STACK 0
java.lang.NullPointerException
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:70)

**Comment by ghost** [comment]
Does that happen with any search?

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 25, 2011 3:42 AM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:

**Comment by jexp** [comment]
Yes, please provide the exact usecase (or better a test-case exposing this).

**Comment by nrkkalyan** [comment]
I tested searching relations it is fine. But when searching for nodes I
felt somewhere it is not properly doing.
I can look into this ASAP if no one is looking to this issue.

Kalyan

On Sun, Dec 25, 2011 at 9:13 AM, Neo4j build server <
reply@reply.github.com

> wrote:
> 
> Does that happen with any search?
> 
> Cheers
> 
> /peter
> 
> Sent from a device with crappy keyboard and autocorrect
> On Dec 25, 2011 3:42 AM, "Radhakrishna Kalyan" <
> reply@reply.github.com>
> wrote:
> 
> > Got the exception when performing Search
> > 
> > Dec 25, 2011 3:38:24 AM org.neo4j.neoclipse.graphdb.GraphDbServiceManager
> > logInfo
> > INFO: connected to embedded neo4j
> > java.util.concurrent.ExecutionException: java.lang.NullPointerException
> >        at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
> >        at java.util.concurrent.FutureTask.get(Unknown Source)
> >        at
> > org.neo4j.neoclipse.search.NeoSearchQuery.run(NeoSearchQuery.java:145)
> >        at
> > 
> > org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
> >        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
> > Caused by: java.lang.NullPointerException
> >        at
> > 
> > org.apache.lucene.util.SimpleStringInterner.intern(SimpleStringInterner.java:54)
> >        at
> > org.apache.lucene.util.StringHelper.intern(StringHelper.java:36)
> >        at org.apache.lucene.index.Term.<init>(Term.java:38)
> >        at
> > 
> > org.apache.lucene.queryParser.QueryParser.getFieldQuery(QueryParser.java:643)
> >        at
> > org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1421)
> >        at
> > org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1309)
> >        at
> > org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1237)
> >        at
> > 
> > org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1226)
> >        at
> > org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
> >        at org.neo4j.index.impl.lucene.IndexType.query(IndexType.java:281)
> >        at
> > org.neo4j.index.impl.lucene.LuceneIndex.query(LuceneIndex.java:207)
> >        at
> > org.neo4j.index.impl.lucene.LuceneIndex.query(LuceneIndex.java:218)
> >        at
> > 
> > org.neo4j.neoclipse.search.NeoSearchQuery.getMatchingNodesFromIndices(NeoSearchQuery.java:196)
> >        at
> > 
> > org.neo4j.neoclipse.search.NeoSearchQuery.access$0(NeoSearchQuery.java:174)
> >        at
> > org.neo4j.neoclipse.search.NeoSearchQuery$1.call(NeoSearchQuery.java:133)
> >        at
> > org.neo4j.neoclipse.search.NeoSearchQuery$1.call(NeoSearchQuery.java:1)
> >        at
> > 
> > org.neo4j.neoclipse.graphdb.GraphDbServiceManager$TaskWrapper.call(GraphDbServiceManager.java:242)
> >        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
> >        at java.util.concurrent.FutureTask.run(Unknown Source)
> >        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown
> > Source)
> >        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
> > Source)
> >        at java.lang.Thread.run(Unknown Source)
> > 
> > ## !SESSION 2011-12-25 03:34:34.650
> > 
> > eclipse.buildId=unknown
> > java.version=1.7.0_01
> > java.vendor=Oracle Corporation
> > BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> > Framework arguments:  -product org.neo4j.neoclipse.neoclipseProduct
> > Command-line arguments:  -product org.neo4j.neoclipse.neoclipseProduct
> > -data C:\Kalyan\github\nrkkalyan\neoclipse\org.neo4j.neoclipse -dev
> > 
> > file:C:/Kalyan/github/nrkkalyan/workspace/.metadata/.plugins/org.eclipse.pde.core/neoclipse.product/dev.properties
> > -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault
> > 
> > !ENTRY org.eclipse.core.jobs 4 2 2011-12-25 03:38:43.892
> > !MESSAGE An internal error occurred during: "Neo4j Search".
> > !STACK 0
> > java.lang.NullPointerException
> >        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:70)
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/issues/16
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/16#issuecomment-3270204

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by ghost** [comment]
Cool,
would be great!

Cheers,

/peter neubauer

Google:neubauer.peter
Skype:peter.neubauer
Phone: +46 704 106975
LinkedIn   http://www.linkedin.com/in/neubauer
Twitter      @peterneubauer

brew install neo4j && neo4j start
heroku addons:add neo4j

On Sun, Dec 25, 2011 at 12:57 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
I tested and observed that if we search without a key and search mode = 'Query' and Node Selected.  

The cause of this is Line 196 in NeoSearchQuery.java 
hits = nodeIndex.query( search.getValueOrQuery() );

It is is causing null pointer, Please let me know if the current implementation in neoclipse is ok or needs to be updated.

**Comment by ghost** [comment]
I think it needs to be updated, possibly asking the user for better input?

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 26, 2011 4:46 PM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:

**Comment by nrkkalyan** [comment]
I felt search is not working as expected.

What I understood is, when one click Search the search panel should appear
and one can able to search for a node or a relation for a given key.

Please let me know if I misunderstood the behavior.

I have not understood the usage of 'Index to Search'  in the search screen.

If you agree with my comments please let me know if I should start working
on this as my next task.

Kalyan

On Mon, Dec 26, 2011 at 4:50 PM, Neo4j build server <
reply@reply.github.com

> wrote:
> 
> I think it needs to be updated, possibly asking the user for better input?
> 
> Cheers
> 
> /peter
> 
> Sent from a device with crappy keyboard and autocorrect
> On Dec 26, 2011 4:46 PM, "Radhakrishna Kalyan" <
> reply@reply.github.com>
> wrote:
> 
> > I tested and observed that if we search without a key and search mode =
> > 'Query' and Node Selected.
> > 
> > The cause of this is Line 196 in NeoSearchQuery.java
> > hits = nodeIndex.query( search.getValueOrQuery() );
> > 
> > It is is causing null pointer, Please let me know if the current
> > implementation in neoclipse is ok or needs to be updated.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275178
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275205

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by ghost** [comment]
I think we should do a different approach.

Just list the indexes, their type and config in a list view or se.
Then, don't provide single index search functionality, instead start
working on the Cypher console that includes Index searches. Better
spent time IMHO.

WDYT?

Cheers,

/peter neubauer

Google:neubauer.peter
Skype:peter.neubauer
Phone: +46 704 106975
LinkedIn   http://www.linkedin.com/in/neubauer
Twitter      @peterneubauer

brew install neo4j && neo4j start
heroku addons:add neo4j

On Mon, Dec 26, 2011 at 11:04 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
As I understood, instead of spending time on modifying the behavior of
current functionality of search , you would like me to work on Cypher
Editor where one can write Cypher query and able to view the results.

Please clarify.

On Tue, Dec 27, 2011 at 9:30 AM, Neo4j build server <
reply@reply.github.com

> wrote:
> 
> I think we should do a different approach.
> 
> Just list the indexes, their type and config in a list view or se.
> Then, don't provide single index search functionality, instead start
> working on the Cypher console that includes Index searches. Better
> spent time IMHO.
> 
> WDYT?
> 
> Cheers,
> 
> /peter neubauer
> 
> Google:neubauer.peter
> Skype:peter.neubauer
> Phone: +46 704 106975
> LinkedIn   http://www.linkedin.com/in/neubauer
> Twitter      @peterneubauer
> 
> brew install neo4j && neo4j start
> heroku addons:add neo4j
> 
> On Mon, Dec 26, 2011 at 11:04 PM, Radhakrishna Kalyan
> reply@reply.github.com
> wrote:
> 
> > I felt search is not working as expected.
> > 
> > What I understood is, when one click Search the search panel should
> > appear
> > and one can able to search for a node or a relation for a given key.
> > 
> > Please let me know if I misunderstood the behavior.
> > 
> > I have not understood the usage of 'Index to Search'  in the search
> > screen.
> > 
> > If you agree with my comments please let me know if I should start
> > working
> > on this as my next task.
> > 
> > Kalyan
> > 
> > On Mon, Dec 26, 2011 at 4:50 PM, Neo4j build server <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > I think it needs to be updated, possibly asking the user for better
> > > input?
> > > 
> > > Cheers
> > > 
> > > /peter
> > > 
> > > Sent from a device with crappy keyboard and autocorrect
> > > On Dec 26, 2011 4:46 PM, "Radhakrishna Kalyan" <
> > > reply@reply.github.com>
> > > wrote:
> > > 
> > > > # I tested and observed that if we search without a key and search mode
> > > > 
> > > > 'Query' and Node Selected.
> > > > 
> > > > The cause of this is Line 196 in NeoSearchQuery.java
> > > > hits = nodeIndex.query( search.getValueOrQuery() );
> > > > 
> > > > It is is causing null pointer, Please let me know if the current
> > > > implementation in neoclipse is ok or needs to be updated.
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275178
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275205
> > 
> > ## 
> > 
> > Thanks and Regards
> > N Radhakrishna Kalyan
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3277153
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/16#issuecomment-3279960

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by ghost** [comment]
Yes,
Exactly. What do you think?

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 27, 2011 7:03 PM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:

**Comment by nrkkalyan** [comment]
Yes It would be a good add on to our tool. I had that in my mind. Ok then I
will start working on that from today.

If you observe there is a small icon in the connection view "SQL" which
will open the query editor this is what I thought initially.

Regards
Kalyan

On Tue, Dec 27, 2011 at 7:07 PM, Neo4j build server <
reply@reply.github.com

> wrote:
> 
> Yes,
> Exactly. What do you think?
> 
> Cheers
> 
> /peter
> 
> Sent from a device with crappy keyboard and autocorrect
> On Dec 27, 2011 7:03 PM, "Radhakrishna Kalyan" <
> reply@reply.github.com>
> wrote:
> 
> > As I understood, instead of spending time on modifying the behavior of
> > current functionality of search , you would like me to work on Cypher
> > Editor where one can write Cypher query and able to view the results.
> > 
> > Please clarify.
> > 
> > On Tue, Dec 27, 2011 at 9:30 AM, Neo4j build server <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > I think we should do a different approach.
> > > 
> > > Just list the indexes, their type and config in a list view or se.
> > > Then, don't provide single index search functionality, instead start
> > > working on the Cypher console that includes Index searches. Better
> > > spent time IMHO.
> > > 
> > > WDYT?
> > > 
> > > Cheers,
> > > 
> > > /peter neubauer
> > > 
> > > Google:neubauer.peter
> > > Skype:peter.neubauer
> > > Phone: +46 704 106975
> > > LinkedIn   http://www.linkedin.com/in/neubauer
> > > Twitter      @peterneubauer
> > > 
> > > brew install neo4j && neo4j start
> > > heroku addons:add neo4j
> > > 
> > > On Mon, Dec 26, 2011 at 11:04 PM, Radhakrishna Kalyan
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > I felt search is not working as expected.
> > > > 
> > > > What I understood is, when one click Search the search panel should
> > > > appear
> > > > and one can able to search for a node or a relation for a given key.
> > > > 
> > > > Please let me know if I misunderstood the behavior.
> > > > 
> > > > I have not understood the usage of 'Index to Search'  in the search
> > > > screen.
> > > > 
> > > > If you agree with my comments please let me know if I should start
> > > > working
> > > > on this as my next task.
> > > > 
> > > > Kalyan
> > > > 
> > > > On Mon, Dec 26, 2011 at 4:50 PM, Neo4j build server <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > I think it needs to be updated, possibly asking the user for better
> > > > > input?
> > > > > 
> > > > > Cheers
> > > > > 
> > > > > /peter
> > > > > 
> > > > > Sent from a device with crappy keyboard and autocorrect
> > > > > On Dec 26, 2011 4:46 PM, "Radhakrishna Kalyan" <
> > > > > reply@reply.github.com>
> > > > > wrote:
> > > > > 
> > > > > > I tested and observed that if we search without a key and search
> > > > > > 
> > > > > > # mode
> > > > > > 
> > > > > > 'Query' and Node Selected.
> > > > > > 
> > > > > > The cause of this is Line 196 in NeoSearchQuery.java
> > > > > > hits = nodeIndex.query( search.getValueOrQuery() );
> > > > > > 
> > > > > > It is is causing null pointer, Please let me know if the current
> > > > > > implementation in neoclipse is ok or needs to be updated.
> > > > > > 
> > > > > > ---
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub:
> > > > > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275178
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3275205
> > > > 
> > > > ## 
> > > > 
> > > > Thanks and Regards
> > > > N Radhakrishna Kalyan
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3277153
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3279960
> > 
> > ## 
> > 
> > Thanks and Regards
> > N Radhakrishna Kalyan
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/issues/16#issuecomment-3283694
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/16#issuecomment-3283722

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by ghost** [comment]
Yes,
Sounds like a plan!

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 27, 2011 7:14 PM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:
