### ISSUE TITLE
Pick a standard location for saving prefs

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/neoclipse#25]
Hi there,
on my computer (OSX) the Neoclipse prefs are saved under /Users/peterneubauer/neoclipse/

This should really be ~/.neoclipse so I think we need to adjust the preference saving a bit ...

**Comment by jexp** [comment]
Or ~/Library/Preferences/neoclipse.

The java preferences Api takes care of that cross platform. Please use it there. 

Von meinem iPhone gesendet

Am 28.01.2012 um 13:15 schrieb Peter Neubauer reply@reply.github.com:

**Comment by nrkkalyan** [comment]
I think its better to save all settings in one place 'user.home/.neoclipse'

**Comment by peterneubauer** [comment]
Yes,
I actually agree there. That is how most programs doing it, would be ok IMHO ...

/peter

On Mon, Mar 19, 2012 at 11:07 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by jexp** [comment]
Why not saving them 

#1 either the eclipse way
#2 or using the java-preferences API which is made exactly for this kind of thing

**Comment by nrkkalyan** [comment]
There is also an xml file which we are creating to save the connection
settings.
I don't know if we can save files using preferences api.

Moreover in one place we are also creating 2 folders for icons. I don't
know the impact of changing it.

Please suggest.

On Mon, Mar 19, 2012 at 11:34 PM, Michael Hunger <
reply@reply.github.com

> wrote:
> 
> Why not saving them
> 
> #1 either the eclipse way
> #2 or using the java-preferences API which is made exactly for this kind
> of thing
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/25#issuecomment-4585304

## 

Thanks and Regards
N Radhakrishna Kalyan
