### ISSUE TITLE
Node property display

### ISSUE THREAD

**Issue by pducrot** [neo4j-contrib/neoclipse#36]
When nodes contain may properties, those are all displayed.
Setting the "Graph Decoration / Node label properties" parameter to only Name doesn't make any difference for me. Is there anything else to change to only display the node name (which is an existing property) and hide non-listed ones?
Cheers,

**Comment by peterneubauer** [comment]
https://vimeo.com/12014944 shows how to do the decorations, name as a label
should be possible (this is on an older version of Neoclipse though).

**Comment by pducrot** [comment]
Thanks for sharing this Peter. I wish this worked for me. 
BTW, I'm running neoclipse-1.8 downloaded 3 last week.
Images are properly displayed in my side too.

**Comment by peterneubauer** [comment]
No, not now. Consider this a feature request, and feel free to pitch in!

**Comment by pducrot** [comment]
Well, I did some java in the past, graph related, but it was on PC using eclipse. I implemented graph algorithms in pipeline pilot for computational chemistry purposes (my actual work) and eventually store graphs in neo4j. This work has now been taken over by someone else. The reason why I picked-up neoclipse recently was to browse the graph without having to use code or to setup a server for this, just look into the graph and check its architecture.
I'm not sure how to start with Xcode, or if you would still be able to do anything useful.

**Comment by peterneubauer** [comment]
Ok,
contact me directly if you need any help or more info, it doesn't really
fit in this issue :)

**Comment by pducrot** [comment]
Hi Peter, 

I'm ready to give it a try. Could you tell me how to start?
As mentioned earlier, I did some java programing in the past (2 years ago) on eclipse (windows) at work.
At home I'm using X-code, but not for java, could you give me some hints to get connected to github from X-code and start looking at neoclipse code and make sure I can compile?

Thanks,
Pierre

**Comment by nrkkalyan** [comment]
Hi,

In order to start compiling the neoclipse code one must have eclipse 3.7 .
Currently Juno is not supported.

All you have to do is just to import as java project and then run as
eclipse plugin application.
If you end up in some errors make sure to check the classpath and add
required plugins.

Let us know how did it go.

Kalyan

On Sun, Nov 25, 2012 at 10:13 PM, Pierre notifications@github.com wrote:

> I'm ready to give it a try. Could you tell me how to start?

## 

Thanks and Regards
N Radhakrishna Kalyan

G/S/T/F:  nrkkalyan
P:  +46 768 800 824
L:   http://www.linkedin.com/in/nrkkalyan

**Comment by pducrot** [comment]
Hi, 

Any preferred between Indigo (Carbon 32 or 64bits), Helios (Carbon 32 or 64bits), Galileo (Carbon 32bits or Cacoa 32 or 64bits), Ganymede (Carbon 32bits) and Europa (Carbon 32bits)? They seem pretty oldish, I'm running MacOS X 10.8.2.

Pierre

**Comment by nrkkalyan** [comment]
It ok with any 3.7 see your os needs

**Comment by peterneubauer** [comment]
Yup,
Indigo is what Neoclipse is building with right now,
http://www.eclipse.org/downloads/packages/release/indigo/sr2

Great to get started, let us know if you need help!

/peter

**Comment by pducrot** [comment]
Ok. Indigo cacoa 64bits. 
Hence, I downloaded the zip file of the lneo4j/neoclipse 1.8 from here: https://github.com/neo4j/neoclipse
Any hints to create the project, upload the files and more importantly add dependencies.
I have a neoclipse folder containing neoclipse, neoclipse.doc, .gitignore pom.xml, etc. which I pointed to while creating a new java project in eclipse, but I guess that's not enough. A full recipe would be appreciated.
Cheers,
Pierre

**Comment by peterneubauer** [comment]
Pierre,
will try to create a screencast today.

**Comment by peterneubauer** [comment]
https://github.com/neo4j/neoclipse/tree/juno/org.neo4j.neoclipse, does that work for you? Otherwise I do a screencast.

**Comment by nrkkalyan** [comment]
No that branch does not work. I created to see if we can able to run
neoclipse in juno.
I will delete that branch

On Tue, Nov 27, 2012 at 2:01 PM, Peter Neubauer notifications@github.comwrote:

> https://github.com/neo4j/neoclipse/tree/juno/org.neo4j.neoclipse, does
> that work for you? Otherwise I do a screencast.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/neo4j/neoclipse/issues/36#issuecomment-10756830.

## 

Thanks and Regards
N Radhakrishna Kalyan

G/S/T/F:  nrkkalyan
P:  +46 768 800 824
L:   http://www.linkedin.com/in/nrkkalyan

**Comment by peterneubauer** [comment]
Well, it does work with Juno 3.8 :)

/peter

**Comment by nrkkalyan** [comment]
Yes. 3.8 works well. Master repo is built with 3.8

Sent from Samsung MobilePeter Neubauer notifications@github.com wrote:Well, it does work with Juno 3.8 :) 

/peter

**Comment by peterneubauer** [comment]
Ok,
will try master then, too.

**Comment by pducrot** [comment]
Hi, first steps are done. Eclipse has been restarted. Where am I suppose to type git clone... "git is not a bash command". Should I first install GIT in eclipse.  I only see support to CVS at the moment.
Pierre 
restart eclipse git clone git://github.com/neo4j/neoclipse.git

checkout branch JUNO git checkout -b juno origin/juno
File→Import→existing project into workspace→point to your checked-out code under org.neo4j.neoclipse/.project

run Neoclipse from inside Eclispe by running neoclipse.product

**Comment by pducrot** [comment]
Sorry all, the problem comes from moutian lion, not eclipse. Don't pay attention to my previous message.
Pierre

**Comment by pducrot** [comment]
Hi, 

Made some progress, did almost all what you described. I'm not familiar with git, and the git checkout command didn't work, so I bypassed it.
I copied the donwloaded (git clone) repository in my eclipse work directory and imported as a new project.
I "ran as an eclipse" application the build.properties file, which properly loanched neoclipse.

It din't seem to compile anything, but work well. How do I force compiling, to see if this works?
Please tell me if I should do differently. Again, I'm not a programer by training, just a scientist that likes and sometimes needs to.

Now I have a couple of questions regarding team programming. There are a few things that I'd like to do - or someone else - such as display only user chosen node or edge properties, or set the icon/image directory preference at the network database level rather than application level. 

How do we proceed, who decide what to put in the next release, what to prioritize? 
Who check code conflicts between participant partial releases? 

Though, I'm not yet sure if I'd be able to do things I'd like to be done, but that's another story.
Cheers,

Pierre

**Comment by nrkkalyan** [comment]
Hi

I can help you and i manage usually the repository. 

I will let you know the dependencies in order to compile the code. Please give me 1-2 hours.

**Comment by pducrot** [comment]
No hurry. Thanks

Pierre

**Comment by nrkkalyan** [comment]
Hi Pierre,

I have created a readme page to the neoclipse repository. Please go through
it and let me know if you were able to follow it.

Your feedback will decide if I can write good read me texts :)

Kalyan

On Wed, Nov 28, 2012 at 10:09 PM, Pierre notifications@github.com wrote:

> No hurry. Thanks
> 
> Pierre
> 
> Le 28 nov. 2012 à 20:52, Radhakrishna Kalyan notifications@github.com a
> écrit :
> 
> > Hi
> > 
> > I can help you and i manage usually the repository.
> > 
> > I will let you know the dependencies in order to compile the code.
> > Please give me 1-2 hours.
> > 
> > Sent from my iPad
> > 
> > On Nov 28, 2012, at 8:04 PM, Pierre notifications@github.com wrote:
> > 
> > > Hi,
> > > 
> > > Made some progress, did almost all what you described. I'm not
> > > familiar with git, and the git checkout command didn't work, so I bypassed
> > > it.
> > > I copied the donwloaded (git clone) repository in my eclipse work
> > > directory and imported as a new project.
> > > I "ran as an eclipse" application the build.properties file, which
> > > properly loanched neoclipse.
> > > 
> > > It din't seem to compile anything, but work well. How do I force
> > > compiling, to see if this works?
> > > Please tell me if I should do differently. Again, I'm not a programer
> > > by training, just a scientist that likes and sometimes needs to.
> > > 
> > > Now I have a couple of questions regarding team programming. There are
> > > a few things that I'd like to do - or someone else - such as display only
> > > user chosen node or edge properties, or set the icon/image directory
> > > preference at the network database level rather than application level.
> > > 
> > > How do we proceed, who decide what to put in the next release, what to
> > > prioritize?
> > > Who check code conflicts between participant partial releases?
> > > 
> > > Though, I'm not yet sure if I'd be able to do things I'd like to be
> > > done, but that's another story.
> > > Cheers,
> > > 
> > > Pierre
> > > 
> > > Le 27 nov. 2012 à 14:01, Peter Neubauer notifications@github.com a
> > > écrit :
> > > 
> > > > https://github.com/neo4j/neoclipse/tree/juno/org.neo4j.neoclipse,
> > > > does that work for you? Otherwise I do a screencast.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/neo4j/neoclipse/issues/36#issuecomment-10821717.

## 

Thanks and Regards
N Radhakrishna Kalyan

G/S/T/F:  nrkkalyan
P:  +46 768 800 824
L:   http://www.linkedin.com/in/nrkkalyan

**Comment by pducrot** [comment]
Hi kalayan,
Thanks for this. Seems to work now. It will probably take a few days to get into the project now. Cheers.
Pierre

**Comment by pducrot** [comment]
Hi,
Would know a tool that would convert the java classes dependencies to a graph format that I could upload in neoclipse or graphviz... that would help getting into the long list of classes :-)
cheers,
Pierre

**Comment by pducrot** [comment]
Hi,

I'm starting coding, since it's not so easy, I'd like to do something simple, such as change de node decoration. Below (or joint) is a snapshot of a type of graph I'm often working on. It's about medicinal chemistry, the graph is composed of molecules, molecular fragments, molecular scaffolds, biological targets and biological activities. Nodes are typed using a "Type" property. A color is also assigned to nodes based on it's type and an image of the molecule or fragment is generated and stored named after the node ID. Edges are typed as well and assigned a color. I build and query the neo4j database directly from a third party application, however, I like using neocplise to browse the database and check the data consistency.

To start with neoclipse java programming, I'd like to :
1. assign node color based on the "Color" property when existing.
2. display only node properties that are listed in the node label list in the preference panel
3. only display the missing Node[0] alter once (rather than as many times as edges) and only if no nodes are to be displayed.

I'll do those in priority and only start 2 if I succeed with 1.

Starting with #1, any hints where to start in neoclipse code?

**Comment by jotomo** [comment]
Hey @pducrot , I'm currently looking into tools to visualize code bases, hence the same you're looking for. Currently I'm playing around with two applications that seem promising, so maybe this is helpful for you:
Stan4j: http://stan4j.com/dependencies/dependency-analysis.html
Looks, good, has issues on Linux x64, works well on Win32, don't know if it has issues on osx.
It's free for non-commerical use and code basses with less than 500 classes (Neoclipse has 162).
Architexa: http://www.architexa.com/learn-more/diagramming-features
Free, creates UML diagrams from code, layer diagrams and control flow.

Taking a quick look (via Stan4j and then the code), src/main/java/org/neo4j/neoclipse/view/NeoGraphLabelProvider.java looks to be in charge of setting the text for a node; so that may serve as a starting point to debug why the node property preferences aren't applied.

**Comment by jotomo** [comment]
@pducrot I read some source and found out why changing preferences to display only certain node properties didn't work for me: I didn't know I had to set the _Filter node properties_ option in the _Database graph_ view (the downward pointing arrow in the right upper corner). Only if that setting is checked the filter is enabled. Could you verify you have this option checked?

**Comment by pducrot** [comment]
@Johannes, 

Thanks for the link, that looks like what I'd like to do.
Pierre

**Comment by pducrot** [comment]
@Johannes, thanks a lot, I've never been curious enough to click on it, expecting here some widow resizing stuff.
That explain why I discovered the code to make these modifications and could change the default display after changing default parameters and recompiling!
Cheers,

**Comment by mike-digian** [comment]
Thanks jotomo.   The filter node properties worked for me too.  This tool is very helpful

![filter node props](https://f.cloud.github.com/assets/4429944/551714/81b4ce04-c331-11e2-8d1a-d511548db71b.png)
