### ISSUE TITLE
Cypher Editor

### ISSUE THREAD

**Issue by nrkkalyan** [neo4j-contrib/neoclipse#7]
Integrate Cypher editor or Sql editor with NoSQL-JDBC  so that one can run queries

**Comment by jexp** [comment]
query results should be rendered tabular or as graph

**Comment by peterneubauer** [comment]
Yay,
much along the lines of
http://rickardoberg.wordpress.com/2011/12/19/creating-a-jdbc-driver-for-neo4j/
with an SQL like view that you could get somewhere!

/peter

On Wed, Dec 21, 2011 at 4:07 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
ya, I was inspired by that post itself. 
And I think its up to the user to choose to see the results as graph or tabular.

**Comment by nrkkalyan** [comment]
The functionality is now added as a to the current version. 
Download 
https://github.com/neo4j/neoclipse/downloads

Happy testing..

**Comment by peterneubauer** [comment]
Cool,
Will do so ASAP!

When we release neo4j 1.6 in a mcouple of weeks, I think you should do a
blog post about all your improvements of neoclipse or do a screencast. WDYT?

On Monday, January 9, 2012, Radhakrishna Kalyan <
reply@reply.github.com>
wrote:

> The functionality is now added as a to the current version.
> Download
> https://github.com/neo4j/neoclipse/downloads
> 
> Happy testing..
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/7#issuecomment-3418510

## 

Cheers,

/peter neubauer

Google:    neubauer.peter
Skype:     peter.neubauer
Phone:     +46 704 106975
LinkedIn:  http://www.linkedin.com/in/neubauer
Twitter:    @peterneubauer
Tungle:    tungle.me/peterneubauer

brew install neo4j && neo4j start
heroku addons:add neo4j

**Comment by nrkkalyan** [comment]
Sure. Will work on that from next week.

**Comment by peterneubauer** [comment]
Love it! Just one comment - could we add a shortcut to execute all cypher in the current view (e.g. ctr+enter) and put that into the tooltip for the run-icon, too? Otherwise, very very neat!

**Comment by nrkkalyan** [comment]
Thank you, I will do that change.

Kalyan

On Thu, Jan 12, 2012 at 3:54 AM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> Love it! Just one comment - could we add a shortcut to execute all cypher
> in the current view (e.g. ctr+enter) and put that into the tooltip for the
> run-icon, too? Otherwise, very very neat!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/issues/7#issuecomment-3457616

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by nrkkalyan** [comment]
Added shortcut to execute the cypher query (Alt+Enter)

**Comment by peterneubauer** [comment]
Great, thank you!

/peter

Sent from my phone, please excuse typos and autocorrection.
On Jan 12, 2012 11:09 AM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:
